openapi: 3.0.3
info:
  title: Kivo API
  description: API for Kivo
  version: 1.0.0
servers:
  - url: https://kivo-api-production.up.railway.app
paths:
  /api/v1/bmc:
    get:
      tags:
        - BMC API
      description: Get all BMCs
      parameters:
        - in: query
          name: is_public
          description: Filter BMCs by public visibility
          required: false
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Success get all BMCs
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BMC'

  /api/v1/bmc/{id}:
    get:
      tags:
        - BMC API
      description: Get BMC by id
      parameters:
        - in: query
          name: is_public
          description: Filter BMCs by public visibility
          required: false
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Success get BMC by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/BMC'

components:
  schemas:
    BMC:
      type: object
      properties:
        id:
          type: string
          format: uuid
        author_id:
          type: string
          format: uuid
        is_public:
          type: boolean
        items:
          type: array
          items:
            type: object
            properties:
              tag:
                type: string
              content:
                type: array
                items:
                  type: string
          example:
            - tag: 'Customer Segments'
              content:
                - content 1
                - content 2
            - tag: 'Value Proposition'
              content:
                - content 1
                - content 2
            - tag: 'Channels'
              content:
                - content 1
                - content 2
            - tag: 'Customer Relationship'
              content:
                - content 1
                - content 2
            - tag: 'Revenue Stream'
              content:
                - content 1
                - content 2
            - tag: 'Key Resources'
              content:
                - content 1
                - content 2
            - tag: 'Key Activities'
              content:
                - content 1
                - content 2
            - tag: 'Key Partnerships'
              content:
                - content 1
                - content 2
            - tag: 'Cost Structure'
              content:
                - content 1
                - content 2
