openapi: 3.0.3
info:
  title: Kivo API
  description: API for Kivo
  version: 1.0.0
servers:
  - url: https://kivo-api-production.up.railway.app
paths:
  /api/v1/bmc:
    post:
      tags:
        - BMC API
      description: Add new BMC
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [full_name]
              properties:
                full_name:
                  type: string
                  minLength: 3
                  maxLength: 255
                nationality:
                  type: string
                  minLength: 3
                  maxLength: 255
                  example: Indonesia
                  nullable: true
      responses:
        201:
          description: Success create BMC
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/BMC'

components:
  schemas:
    BMC:
      type: object
      properties:
        id:
          type: string
          format: uuid
        coordinates:
          type: object
          properties:
            lat:
              type: string
            long:
              type: string
            alt:
              type: string
        author_id:
          type: string
          format: uuid
        is_public:
          type: boolean
        items:
          type: array
          items:
            type: object
            properties:
              tag:
                type: string
              content:
                type: array
                items:
                  type: string
            example:
              - tag: 'Customer Segments'
                content:
                  - content 1
                  - content 2
              - tag: 'Value Proposition'
                content:
                  - content 1
                  - content 2
              - tag: 'Channels'
                content:
                  - content 1
                  - content 2
              - tag: 'Customer Relationship'
                content:
                  - content 1
                  - content 2
              - tag: 'Revenue Stream'
                content:
                  - content 1
                  - content 2
              - tag: 'Key Resources'
                content:
                  - content 1
                  - content 2
              - tag: 'Key Activities'
                content:
                  - content 1
                  - content 2
              - tag: 'Key Partnerships'
                content:
                  - content 1
                  - content 2
              - tag: 'Cost Structure'
                content:
                  - content 1
                  - content 2
